<?php
session_start();
if (!isset($_SESSION['user_id']) || $_SESSION['role'] !== 'admin') {
    header('Location: ../login.php');
    exit();
}

include '../config.php';

$type = $_GET['type'] ?? '';
$format = $_GET['format'] ?? '';
$month = $_GET['month'] ?? '';
$category = $_GET['category'] ?? '';

// Build query based on type
$where_conditions = ["a.status = 'published'"];
$report_title = "Laporan Artikel";

if ($type == 'monthly' && !empty($month)) {
    $where_conditions[] = "DATE_FORMAT(a.created_at, '%Y-%m') = '$month'";
    $report_title = "Laporan Artikel Bulan " . date('F Y', strtotime($month . '-01'));
} elseif ($type == 'category' && !empty($category)) {
    $category_escaped = mysqli_real_escape_string($conn, $category);
    $where_conditions[] = "a.kategori = '$category_escaped'";
    $report_title = "Laporan Artikel Kategori: " . $category;
}

$where_clause = 'WHERE ' . implode(' AND ', $where_conditions);
$query = "SELECT a.*, u.nama FROM artikel a LEFT JOIN users u ON a.author_id = u.id $where_clause ORDER BY a.created_at DESC";
$result = mysqli_query($conn, $query);

if ($format == 'excel') {
    // CSV Export (Excel compatible)
    header('Content-Type: text/csv; charset=utf-8');
    header('Content-Disposition: attachment; filename="' . str_replace(' ', '_', $report_title) . '.csv"');
    
    // Output UTF-8 BOM for proper Excel encoding
    echo "\xEF\xBB\xBF";
    
    // CSV Headers
    echo "No,Judul Artikel,Penulis,Kategori,Tanggal Publish\n";
    
    $no = 1;
    while($row = mysqli_fetch_assoc($result)) {
        // Escape CSV values
        $judul = '"' . str_replace('"', '""', $row['judul']) . '"';
        $penulis = '"' . str_replace('"', '""', $row['nama'] ?? 'Unknown') . '"';
        $kategori = '"' . str_replace('"', '""', $row['kategori'] ?? '-') . '"';
        $tanggal = date('d/m/Y', strtotime($row['created_at']));
        
        echo $no++ . "," . $judul . "," . $penulis . "," . $kategori . "," . $tanggal . "\n";
    }
    
} elseif ($format == 'pdf') {
    // HTML Export for PDF (user can print to PDF)
    ?>
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title><?php echo $report_title; ?></title>
        <style>
            @media print {
                body { margin: 0; }
                .no-print { display: none; }
            }
            body { font-family: Arial, sans-serif; margin: 20px; }
            h1 { text-align: center; color: #333; margin-bottom: 10px; }
            .header { text-align: center; margin-bottom: 30px; }
            table { width: 100%; border-collapse: collapse; margin-top: 20px; }
            th, td { border: 1px solid #ddd; padding: 8px; text-align: left; font-size: 12px; }
            th { background-color: #f2f2f2; font-weight: bold; }
            .footer { margin-top: 30px; text-align: center; font-size: 10px; color: #666; }
            .print-btn { background: #dc3545; color: white; padding: 10px 20px; border: none; border-radius: 5px; cursor: pointer; margin: 20px; }
        </style>
    </head>
    <body>
        <div class="no-print">
            <button class="print-btn" onclick="window.print()">Print/Save as PDF</button>
            <button class="print-btn" onclick="window.close()" style="background: #6c757d;">Close</button>
        </div>
        
        <div class="header">
            <h1><?php echo $report_title; ?></h1>
            <p>Tanggal Export: <?php echo date('d F Y'); ?></p>
        </div>
        
        <table>
            <thead>
                <tr>
                    <th width="5%">No</th>
                    <th width="40%">Judul Artikel</th>
                    <th width="20%">Penulis</th>
                    <th width="15%">Kategori</th>
                    <th width="20%">Tanggal Publish</th>
                </tr>
            </thead>
            <tbody>
                <?php 
                $no = 1;
                while($row = mysqli_fetch_assoc($result)): 
                ?>
                <tr>
                    <td><?php echo $no++; ?></td>
                    <td><?php echo htmlspecialchars($row['judul']); ?></td>
                    <td><?php echo htmlspecialchars($row['nama'] ?? 'Unknown'); ?></td>
                    <td><?php echo htmlspecialchars($row['kategori'] ?? '-'); ?></td>
                    <td><?php echo date('d/m/Y', strtotime($row['created_at'])); ?></td>
                </tr>
                <?php endwhile; ?>
            </tbody>
        </table>
        
        <div class="footer">
            <p>Portal Artikel Sekolah - Generated by Admin</p>
        </div>
    </body>
    </html>
    <?php
} else {
    header('Location: laporan.php');
}
?>